---
- name: Ejection des Disques
  command: "qm set {{vm_id}} --delete ide2 --delete ide3 --delete sata3"
  become: true

- name: Suppression de l'ISO
  file:
    path: /mnt/pve/ZPOOL-FREENASHDD01/template/iso/{{template_name}}Provision.iso
    state: absent