- hosts: proxmox
  vars_files: 
    - ../host_vars/proxmox.yml
    - ../roles/SQL/vars/SQL.yml

  tasks:
  - name: Déploiement de la VM
    include_tasks: ../roles/SQL/tasks/VM.yml

  - name: Forcer le rafraîchissement de l'inventaire
    meta: refresh_inventory

  - name: 2 Min de pause
    ansible.builtin.pause:
      minutes: 2

- hosts: windows
  vars_files: 
    - ../roles/SQL/vars/SQL.yml

  tasks:
  - name: Ajout du serveur SQL au domaine
    include_tasks: ../roles/SQL/tasks/ajout_domaine.yml
  
  - name: 1 Min de pause
    ansible.builtin.pause:
      minutes: 1

- hosts: proxmox
  vars_files: 
    - ../roles/SQL/vars/SQL.yml

  tasks:
  - name: Modification du fichier inventaire du serveur SQL
    include_tasks: ../roles/SQL/tasks/modif_host.yml

  - name: Forcer le rafraîchissement de l'inventaire
    meta: refresh_inventory

- hosts: windows
  vars_files: 
    - ../roles/SQL/vars/SQL.yml

  tasks:
  - name: Config du Windows
    include_tasks: ../roles/SQL/tasks/config.yml

  - name: 2 Min de pause
    ansible.builtin.pause:
      minutes: 2

  - name: Installation de SQL 2017 et SSMS
    include_tasks: ../roles/SQL/tasks/SQL2017.yml

  - name: Installation Sage côté serveur SQL
    include_tasks: ../roles/SQL/tasks/ServSage.yml

  - name: Désactivation et fermeture du port WinRM
    include_tasks: ../roles/SQL/tasks/desac_winrm.yml

- hosts: proxmox
  vars_files: 
    - ../host_vars/proxmox.yml
    - ../roles/SQL/vars/SQL.yml

  tasks:
  - name: Détachement des disques de la VM et suppression de l'ISO temporaire
    include_tasks: ../roles/SQL/tasks/cleanup.yml